"""
    Pinterest REST API

    Pinterest's REST API  # noqa: E501

    The version of the OpenAPI document: 5.5.0
    Contact: pinterest-api@pinterest.com
    Generated by: https://openapi-generator.tech
"""


from setuptools import setup, find_packages  # noqa: H301

NAME = "Pinterest Generated Client"
VERSION = "0.1.2-wip"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = [
  "urllib3==1.26.12",
  "python-dateutil",
]

setup(
    name=NAME,
    version=VERSION,
    description="Pinterest REST API",
    author="Pinterest, Inc.",
    author_email="pinterest-api@pinterest.com",
<<<<<<< Updated upstream
    url="",
=======
    url="https://github.com/pinterest/pinterest-python-generated-api-client/",
>>>>>>> Stashed changes
    keywords=["OpenAPI", "OpenAPI-Generator", "Pinterest REST API"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    license="MIT",
    long_description="""\
    Pinterest&#39;s REST API  # noqa: E501
    """
)
