"""
    Pinterest REST API

    Pinterest's REST API  # noqa: E501

    The version of the OpenAPI document: 5.15.0
    Contact: pinterest-api@pinterest.com
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from openapi_generated.pinterest_client.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
    OpenApiModel
)
from openapi_generated.pinterest_client.exceptions import ApiAttributeError


def lazy_import():
    from openapi_generated.pinterest_client.model.currency import Currency
    globals()['Currency'] = Currency


class BillingInvoiceResponse(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
        ('document_type',): {
            'INVOICE': "INVOICE",
            'CREDIT_MEMO': "CREDIT_MEMO",
        },
        ('status',): {
            'OPEN': "OPEN",
            'CLOSED': "CLOSED",
        },
    }

    validations = {
        ('id',): {
            'regex': {
                'pattern': r'^\d+$',  # noqa: E501
            },
        },
        ('ad_account_id',): {
            'regex': {
                'pattern': r'^\d+$',  # noqa: E501
            },
        },
        ('billing_period_start_date',): {
            'regex': {
                'pattern': r'^(\d{4})-(\d{2})-(\d{2})$',  # noqa: E501
            },
        },
        ('billing_period_end_date',): {
            'regex': {
                'pattern': r'^(\d{4})-(\d{2})-(\d{2})$',  # noqa: E501
            },
        },
        ('invoice_due_date',): {
            'regex': {
                'pattern': r'^(\d{4})-(\d{2})-(\d{2})$',  # noqa: E501
            },
        },
    }

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        lazy_import()
        return (bool, date, datetime, dict, float, int, list, str, none_type,)  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'id': (str,),  # noqa: E501
            'ad_account_id': (str,),  # noqa: E501
            'ad_account_name': (str,),  # noqa: E501
            'document_type': (str,),  # noqa: E501
            'amount_billed_micro_currency': (int,),  # noqa: E501
            'amount_tax_micro_currency': (int, none_type,),  # noqa: E501
            'amount_net_micro_currency': (int, none_type,),  # noqa: E501
            'amount_discount_micro_currency': (int, none_type,),  # noqa: E501
            'currency': (Currency,),  # noqa: E501
            'billing_period_start_date': (date,),  # noqa: E501
            'billing_period_end_date': (date,),  # noqa: E501
            'invoice_due_date': (date,),  # noqa: E501
            'status': (str,),  # noqa: E501
            'payment_terms': (str,),  # noqa: E501
            'bill_to_country': (str,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'id': 'id',  # noqa: E501
        'ad_account_id': 'ad_account_id',  # noqa: E501
        'ad_account_name': 'ad_account_name',  # noqa: E501
        'document_type': 'document_type',  # noqa: E501
        'amount_billed_micro_currency': 'amount_billed_micro_currency',  # noqa: E501
        'amount_tax_micro_currency': 'amount_tax_micro_currency',  # noqa: E501
        'amount_net_micro_currency': 'amount_net_micro_currency',  # noqa: E501
        'amount_discount_micro_currency': 'amount_discount_micro_currency',  # noqa: E501
        'currency': 'currency',  # noqa: E501
        'billing_period_start_date': 'billing_period_start_date',  # noqa: E501
        'billing_period_end_date': 'billing_period_end_date',  # noqa: E501
        'invoice_due_date': 'invoice_due_date',  # noqa: E501
        'status': 'status',  # noqa: E501
        'payment_terms': 'payment_terms',  # noqa: E501
        'bill_to_country': 'bill_to_country',  # noqa: E501
    }

    read_only_vars = {
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, *args, **kwargs):  # noqa: E501
        """BillingInvoiceResponse - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            id (str): Unique identifier for the billing invoice. [optional]  # noqa: E501
            ad_account_id (str): The ID of the ad account this invoice belongs to. [optional]  # noqa: E501
            ad_account_name (str): The name of the ad account this invoice belongs to. [optional]  # noqa: E501
            document_type (str): The type of the document. [optional]  # noqa: E501
            amount_billed_micro_currency (int): The amount billed in this invoice. Denoted in micro currency. [optional]  # noqa: E501
            amount_tax_micro_currency (int, none_type): The tax in this invoice. Denoted in micro currency. [optional]  # noqa: E501
            amount_net_micro_currency (int, none_type): The net amount in this invoice. Denoted in micro currency. [optional]  # noqa: E501
            amount_discount_micro_currency (int, none_type): The discount in this invoice. Denoted in micro currency. [optional]  # noqa: E501
            currency (Currency): [optional]  # noqa: E501
            billing_period_start_date (date): The start date of the billing period. Format: YYYY-MM-DD. [optional]  # noqa: E501
            billing_period_end_date (date): The end date of the billing period. Format: YYYY-MM-DD. [optional]  # noqa: E501
            invoice_due_date (date): The date the invoice is due. Format: YYYY-MM-DD. [optional]  # noqa: E501
            status (str): The status of the invoice. [optional]  # noqa: E501
            payment_terms (str): The payment terms of the invoice. [optional]  # noqa: E501
            bill_to_country (str): The country of the bill to address. [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, *args, **kwargs):  # noqa: E501
        """BillingInvoiceResponse - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            id (str): Unique identifier for the billing invoice. [optional]  # noqa: E501
            ad_account_id (str): The ID of the ad account this invoice belongs to. [optional]  # noqa: E501
            ad_account_name (str): The name of the ad account this invoice belongs to. [optional]  # noqa: E501
            document_type (str): The type of the document. [optional]  # noqa: E501
            amount_billed_micro_currency (int): The amount billed in this invoice. Denoted in micro currency. [optional]  # noqa: E501
            amount_tax_micro_currency (int, none_type): The tax in this invoice. Denoted in micro currency. [optional]  # noqa: E501
            amount_net_micro_currency (int, none_type): The net amount in this invoice. Denoted in micro currency. [optional]  # noqa: E501
            amount_discount_micro_currency (int, none_type): The discount in this invoice. Denoted in micro currency. [optional]  # noqa: E501
            currency (Currency): [optional]  # noqa: E501
            billing_period_start_date (date): The start date of the billing period. Format: YYYY-MM-DD. [optional]  # noqa: E501
            billing_period_end_date (date): The end date of the billing period. Format: YYYY-MM-DD. [optional]  # noqa: E501
            invoice_due_date (date): The date the invoice is due. Format: YYYY-MM-DD. [optional]  # noqa: E501
            status (str): The status of the invoice. [optional]  # noqa: E501
            payment_terms (str): The payment terms of the invoice. [optional]  # noqa: E501
            bill_to_country (str): The country of the bill to address. [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
