"""
    Pinterest REST API

    Pinterest's REST API  # noqa: E501

    The version of the OpenAPI document: 5.17.0
    Contact: pinterest-api@pinterest.com
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from openapi_generated.pinterest_client.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
    OpenApiModel
)
from openapi_generated.pinterest_client.exceptions import ApiAttributeError



class ConversionEventDeviceInfo(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
        ('form_factor',): {
            'DESKTOP': "desktop",
            'LAPTOP': "laptop",
            'CELLPHONE': "cellphone",
            'TABLET': "tablet",
            'SMARTWATCH': "smartwatch",
            'TV': "tv",
            'VR': "vr",
            'CONSOLE': "console",
            'OTHER': "other",
        },
        ('os_family',): {
            'IOS': "ios",
            'ANDROID': "android",
            'MACOS': "macos",
            'WINDOWS': "windows",
            'LINUX': "linux",
            'BSD': "bsd",
            'OTHER': "other",
        },
        ('network_type',): {
            'WIFI': "wifi",
            'CELLULAR_2G': "cellular_2g",
            'CELLULAR_3G': "cellular_3g",
            'CELLULAR_4G': "cellular_4g",
            'CELLULAR_5G': "cellular_5g",
            'CELLULAR_6G': "cellular_6g",
            'ETHERNET': "ethernet",
            'UNKNOWN': "unknown",
        },
    }

    validations = {
        ('brand',): {
            'max_length': 100,
        },
        ('type',): {
            'max_length': 100,
        },
        ('model',): {
            'max_length': 100,
        },
        ('os_name',): {
            'max_length': 100,
        },
        ('os_version',): {
            'max_length': 100,
        },
        ('os_release_name',): {
            'max_length': 100,
        },
        ('kernel_version',): {
            'max_length': 100,
        },
        ('carrier',): {
            'max_length': 100,
        },
        ('screen_width',): {
            'inclusive_maximum': 30720,
            'inclusive_minimum': 0,
        },
        ('screen_height',): {
            'inclusive_maximum': 30720,
            'inclusive_minimum': 0,
        },
        ('screen_density',): {
            'inclusive_maximum': 100000,
            'inclusive_minimum': 0,
        },
        ('cpu_cores',): {
            'inclusive_maximum': 1152,
            'inclusive_minimum': 0,
        },
        ('storage_size',): {
            'inclusive_maximum': 1048576,
            'inclusive_minimum': 0,
        },
        ('storage_free_space',): {
            'inclusive_maximum': 1048576,
            'inclusive_minimum': 0,
        },
        ('external_storage_size',): {
            'inclusive_maximum': 1048576,
            'inclusive_minimum': 0,
        },
        ('external_storage_free_space',): {
            'inclusive_maximum': 1048576,
            'inclusive_minimum': 0,
        },
        ('locale',): {
            'max_length': 35,
        },
        ('languages',): {
            'max_items': 100,
            'min_items': 0,
        },
        ('timezone',): {
            'max_length': 40,
        },
        ('timezone_abbr',): {
            'max_length': 5,
        },
        ('battery_level',): {
            'inclusive_maximum': 100,
            'inclusive_minimum': 0,
        },
    }

    additional_properties_type = None

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        return {
            'brand': (str,),  # noqa: E501
            'type': (str,),  # noqa: E501
            'model': (str,),  # noqa: E501
            'form_factor': (str,),  # noqa: E501
            'os_family': (str,),  # noqa: E501
            'os_name': (str,),  # noqa: E501
            'os_version': (str,),  # noqa: E501
            'os_release_name': (str,),  # noqa: E501
            'kernel_version': (str,),  # noqa: E501
            'carrier': (str,),  # noqa: E501
            'screen_width': (int,),  # noqa: E501
            'screen_height': (int,),  # noqa: E501
            'screen_density': (int,),  # noqa: E501
            'cpu_cores': (int,),  # noqa: E501
            'storage_size': (int,),  # noqa: E501
            'storage_free_space': (int,),  # noqa: E501
            'external_storage_size': (int,),  # noqa: E501
            'external_storage_free_space': (int,),  # noqa: E501
            'locale': (str,),  # noqa: E501
            'languages': ([str],),  # noqa: E501
            'timezone': (str,),  # noqa: E501
            'timezone_abbr': (str,),  # noqa: E501
            'network_type': (str,),  # noqa: E501
            'battery_level': (int,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'brand': 'brand',  # noqa: E501
        'type': 'type',  # noqa: E501
        'model': 'model',  # noqa: E501
        'form_factor': 'form_factor',  # noqa: E501
        'os_family': 'os_family',  # noqa: E501
        'os_name': 'os_name',  # noqa: E501
        'os_version': 'os_version',  # noqa: E501
        'os_release_name': 'os_release_name',  # noqa: E501
        'kernel_version': 'kernel_version',  # noqa: E501
        'carrier': 'carrier',  # noqa: E501
        'screen_width': 'screen_width',  # noqa: E501
        'screen_height': 'screen_height',  # noqa: E501
        'screen_density': 'screen_density',  # noqa: E501
        'cpu_cores': 'cpu_cores',  # noqa: E501
        'storage_size': 'storage_size',  # noqa: E501
        'storage_free_space': 'storage_free_space',  # noqa: E501
        'external_storage_size': 'external_storage_size',  # noqa: E501
        'external_storage_free_space': 'external_storage_free_space',  # noqa: E501
        'locale': 'locale',  # noqa: E501
        'languages': 'languages',  # noqa: E501
        'timezone': 'timezone',  # noqa: E501
        'timezone_abbr': 'timezone_abbr',  # noqa: E501
        'network_type': 'network_type',  # noqa: E501
        'battery_level': 'battery_level',  # noqa: E501
    }

    read_only_vars = {
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, *args, **kwargs):  # noqa: E501
        """ConversionEventDeviceInfo - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            brand (str): Device brand. [optional]  # noqa: E501
            type (str): Device type. [optional]  # noqa: E501
            model (str): Device model name. [optional]  # noqa: E501
            form_factor (str): Device form factor. [optional]  # noqa: E501
            os_family (str): OS Family. [optional]  # noqa: E501
            os_name (str): Short name of the OS. This value if specific to os family. Examples: Windows: 10, 11; Android: 16; iOS: 18; MacOS: 15; Linux: Debian, Ubuntu, Arch. [optional]  # noqa: E501
            os_version (str): Full name of the version. Examples: iOS: 18.3 Android: 16.1 MacOS: 15.5 Windows: 24H2 Ubuntu Linux: 25.04. [optional]  # noqa: E501
            os_release_name (str): Marketing name for the release version iOS: Dawn Android: Baklava MacOS: Sequoia Ubuntu Linux: Plucky Puffin. [optional]  # noqa: E501
            kernel_version (str): Kernel version. Examples: Linux: 6.15. Obtain by running: uname -r MacOS: 24.3.0. Obtain by running: sysctl kern.version Android: 6.6. Obtain from OS.uname().release. [optional]  # noqa: E501
            carrier (str): User device's mobile carrier.. [optional]  # noqa: E501
            screen_width (int): Screen width in pixels. [optional]  # noqa: E501
            screen_height (int): Screen height in pixels. [optional]  # noqa: E501
            screen_density (int): Screen density, PPI. [optional]  # noqa: E501
            cpu_cores (int): Number of CPU cores. [optional]  # noqa: E501
            storage_size (int): Internal storage size in GB. [optional]  # noqa: E501
            storage_free_space (int): Internal storage size in GB. [optional]  # noqa: E501
            external_storage_size (int): External storage size in GB. [optional]  # noqa: E501
            external_storage_free_space (int): External storage size in GB. [optional]  # noqa: E501
            locale (str): Device locale BCP-47 format. [optional]  # noqa: E501
            languages ([str]): List of user installed languages. ISO 639-1 format. [optional]  # noqa: E501
            timezone (str): Device timezone. [optional]  # noqa: E501
            timezone_abbr (str): Timezone abbreviation. [optional]  # noqa: E501
            network_type (str): Network type: 4G, 5G, ethernet, wifi In Android: NetworkCapabilities.getNetworkCapabilities(). [optional]  # noqa: E501
            battery_level (int): Battery charge level percentage. [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, *args, **kwargs):  # noqa: E501
        """ConversionEventDeviceInfo - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            brand (str): Device brand. [optional]  # noqa: E501
            type (str): Device type. [optional]  # noqa: E501
            model (str): Device model name. [optional]  # noqa: E501
            form_factor (str): Device form factor. [optional]  # noqa: E501
            os_family (str): OS Family. [optional]  # noqa: E501
            os_name (str): Short name of the OS. This value if specific to os family. Examples: Windows: 10, 11; Android: 16; iOS: 18; MacOS: 15; Linux: Debian, Ubuntu, Arch. [optional]  # noqa: E501
            os_version (str): Full name of the version. Examples: iOS: 18.3 Android: 16.1 MacOS: 15.5 Windows: 24H2 Ubuntu Linux: 25.04. [optional]  # noqa: E501
            os_release_name (str): Marketing name for the release version iOS: Dawn Android: Baklava MacOS: Sequoia Ubuntu Linux: Plucky Puffin. [optional]  # noqa: E501
            kernel_version (str): Kernel version. Examples: Linux: 6.15. Obtain by running: uname -r MacOS: 24.3.0. Obtain by running: sysctl kern.version Android: 6.6. Obtain from OS.uname().release. [optional]  # noqa: E501
            carrier (str): User device's mobile carrier.. [optional]  # noqa: E501
            screen_width (int): Screen width in pixels. [optional]  # noqa: E501
            screen_height (int): Screen height in pixels. [optional]  # noqa: E501
            screen_density (int): Screen density, PPI. [optional]  # noqa: E501
            cpu_cores (int): Number of CPU cores. [optional]  # noqa: E501
            storage_size (int): Internal storage size in GB. [optional]  # noqa: E501
            storage_free_space (int): Internal storage size in GB. [optional]  # noqa: E501
            external_storage_size (int): External storage size in GB. [optional]  # noqa: E501
            external_storage_free_space (int): External storage size in GB. [optional]  # noqa: E501
            locale (str): Device locale BCP-47 format. [optional]  # noqa: E501
            languages ([str]): List of user installed languages. ISO 639-1 format. [optional]  # noqa: E501
            timezone (str): Device timezone. [optional]  # noqa: E501
            timezone_abbr (str): Timezone abbreviation. [optional]  # noqa: E501
            network_type (str): Network type: 4G, 5G, ethernet, wifi In Android: NetworkCapabilities.getNetworkCapabilities(). [optional]  # noqa: E501
            battery_level (int): Battery charge level percentage. [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
